-- Migration: Create casino betting tables
CREATE TABLE IF NOT EXISTS casino_bet_orders (
  id INT(11) NOT NULL AUTO_INCREMENT,
  transaction_id VARCHAR(100) NOT NULL,
  user_id INT(11) NOT NULL,
  api_provider VARCHAR(100) NOT NULL,
  vendor_id INT(11) DEFAULT NULL,
  vendor_name VARCHAR(100) NOT NULL,
  game_type VARCHAR(50) NOT NULL,
  table_name VARCHAR(100) DEFAULT NULL,
  before_bet_money DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  bet_money DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  after_bet_money DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  before_win_money DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  win_money DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  after_win_money DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  bet_status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1=win, 2=lose, 3=cancelled, 4=tie, 5=empty_bet',
  note TEXT DEFAULT NULL,
  bet_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  result_time TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cbo_transaction_id (transaction_id),
  KEY idx_cbo_user_id (user_id),
  KEY idx_cbo_vendor_id (vendor_id),
  KEY idx_cbo_bet_time (bet_time),
  KEY idx_cbo_bet_status (bet_status),
  CONSTRAINT fk_cbo_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_cbo_vendor FOREIGN KEY (vendor_id) REFERENCES providers (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
